version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=DEBmbwkSrzy9D1T9cJfa
      
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

  mailserver:
    image: djfarrelly/maildev
    container_name: mailserver
    ports:
      - "25:25"
      - "4000:80"

  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y 

  customermanagementapi:
    image: airport/customermanagementapi:latest
    build: 
      context: .
      dockerfile: CustomerManagementAPI/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  flightmanagementapi:
    image: airport/flightmanagementapi:latest
    build: 
      context: .
      dockerfile: FlightManagementAPI/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  rentalmanagementapi:
    image: airport/rentalmanagementapi:latest
    build: 
      context: .
      dockerfile: RentalManagementAPI/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  invoiceservice:
    image: airport/invoiceservice:latest
    build: 
      context: .
      dockerfile: InvoiceService/Dockerfile
    container_name: invoiceservice
    depends_on:
      - rabbitmq
      - sqlserver
      - mailserver
    environment:
      - DOTNET_ENVIRONMENT=Production

  notificationservice:
    image: airport/notificationservice:latest
    build: 
      context: .
      dockerfile: NotificationService/Dockerfile
    container_name: notificationservice
    depends_on:
      - rabbitmq
      - sqlserver
      - mailserver
    environment:
      - DOTNET_ENVIRONMENT=Production

  rentalservice:
    image: airport/rentalservice:latest
    build: 
      context: .
      dockerfile: RentalService/Dockerfile
    container_name: rentalservice
    depends_on:
      - rabbitmq
      - sqlserver
      - mailserver
    environment:
      - DOTNET_ENVIRONMENT=Production

  securityservice:
    image: airport/securityservice:latest
    build: 
      context: .
      dockerfile: SecurityService/Dockerfile
    container_name: securityservice
    depends_on:
      - rabbitmq
      - sqlserver
      - mailserver
    environment:
      - DOTNET_ENVIRONMENT=Production

volumes:
  sqlserverdata:
    external: true    
  rabbitmqdata:
    external: true